name: deploy-to-sagemaker
on: 
  workflow-dispatch:
    dummy:
      required: false
      default: 'dummy'
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install depedencies
        run: |
          pip install --pre bentoml
          pip install --pre bentoctl
          pip install boto3
          bentoctl operator install aws-sagemaker
      - name: build bento and bentoctl deployable
        run: |
          pip install -r ./requirements.txt
          python ./train.py
          bentoml build -f bentofile.yaml
          bentoctl build -b iris_classifier:latest --dry-run -f ./sagemaker_config.yaml
      - run: |
          IMG=$(docker image list --format "{{json .Tag}}" | head -1 | tr -d '"')
          docker run aws-sagemaker-iris_classifier:$IMG ls
          docker run aws-sagemaker-iris_classifier:$IMG bash -c 'echo $PATH; echo $BENTO_PATH'
